language: python

env:
    global:
        - UNICODE_WIDTH=32
        - PLAT=x86_64
        - VERSION=$(echo $TRAVIS_TAG | sed s/v//)
    matrix:
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_VERSION=3.4
        - MB_PYTHON_VERSION=3.5
        - MB_PYTHON_VERSION=3.6
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

services: docker
sudo: required

matrix:
    fast_finish: true
    exclude:
        - os: osx
        - os: linux
          compiler: clang
    include:
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=2.7
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.4
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.5
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.6

addons:
    apt:
      sources:
        - sourceline: 'ppa:jokva/backports'
        - george-edison55-precise-backports # cmake 3
      packages:
        - valgrind
        - cppcheck
        - cmake
        - cmake-data

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update && brew install cppcheck;
    fi
  - pip install -r requirements.txt

before_script:
  - enabled="-DBUILD_PYTHON=OFF -DBUILD_MEX=OFF"
  - if [[ -n "${MB_PYTHON_VERSION+1}" ]]; then
        enabled="$enabled -DBUILD_PYTHON=ON -DREQUIRE_PYTHON=ON";
    fi
  - cmake --version
  - mkdir build
  - pushd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_BUILD_TYPE=Release
          $enabled ..
  - cppcheck --language=c
             --std=c99
             --enable=style,portability,performance,warning
             --library=posix
             --library=$TRAVIS_BUILD_DIR/cppcheck/segyio.cfg
             --suppressions-list=$TRAVIS_BUILD_DIR/cppcheck/suppressions.txt
             --inline-suppr
             --project=compile_commands.json
             --error-exitcode=1
  - popd

# distutils/setuptools on macos ignores the --rpath argument, so set
# DYLD_LIBRARY_PATH so that the freshly-built image is picked up on for the
# tests
script:
  - pushd build
  - export DYLD_LIBRARY_PATH=$PWD/lib
  - make && ctest --output-on-failure
  - sudo make install
  - popd
  - build_wheel . $PLAT
  - install_run $PLAT
  - mv wheelhouse dist

before_deploy:
  # OS X ships with a tar that doesn't support --exclude-vcs, which is
  # unproblematic as long as source code is uploaded from linux.
  - if [[ "$TRAVIS_OS_NAME" == "linux" && ! -d segyio-$VERSION ]]; then
      git clone $TRAVIS_BUILD_DIR segyio-$VERSION;
      echo "version = '$TRAVIS_TAG'" > segyio-$VERSION/python/segyio/version.py;
      tar --exclude-vcs -C $TRAVIS_BUILD_DIR -czvf segyio-$VERSION.tar.gz segyio-$VERSION;
      zip --exclude *.git -r segyio-$VERSION.zip $TRAVIS_BUILD_DIR/segyio-$VERSION/*;
    fi

deploy:
    - provider: pypi # source distribution (done from linux python 3.6 only)
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      password:
        secure: WHeA5x2iiXzjYXdgZeJU6l4fawRi/umqH1713QAj0RPZBAnD+9m8Zrpn2UWn9+1dtx6xUMkNg3ZTueVKTKo0f2i/4o0xkzQ5BW11cetCWusV2Dku1btPTA5Fhs+dvPDlL3m496a3Bq/A/fRDj5JLDiiPibvpM01lEBxFKYooWGQ75HVuhnAt57vabD45gDpIE7N23+So4+9bsG/nT/ZlgoaS01uLTdlnf6tjNgP0/UBkonmedC62iVvCu7itfHZMTY2rSeww7KBMI3s7Gz+cyx9IbI3shbDpdJGHpM8Qe+1oFi31Z+DylWQA5SkpHlLMUP+zjMKLF+1hXGNUeJuyadIFrxzbS3vTV2yRPa6ol8q+bX7YLy0xNLSE8aMm54LKgXfRKLc3G8d3I33oEfyk5hygY8iEX728r2TsARslYxOF3sZqJvY8lx4GBEDiXxX2GJvGCPy/Uby786uWnZlFFkDERk3nawE0W68zY0GElbutq6HMSk6v49J7em9Rg/QLptjoa0uF2A9Cy+BAJcnfauIawOG3UPXZ8kD60PTbu8tqtwtXO5lzTSIOr1lt3+6R8GmCc2hz2YXELKvdnZWYCXAjnNuC4eESlp7zxmzhpOVkb2Jy1v6rGKpcxVMggLQbOjOGWPLg9q4+OZQBw5bhMGmVGQhSBuxzEb/wBRy9XV8=
      on:
        condition: $TRAVIS_OS_NAME == linux && $MB_PYTHON_VERSION == 3.6
        tags: true

    - provider: pypi # upload built wheels
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      distributions: build
      password:
        secure: WHeA5x2iiXzjYXdgZeJU6l4fawRi/umqH1713QAj0RPZBAnD+9m8Zrpn2UWn9+1dtx6xUMkNg3ZTueVKTKo0f2i/4o0xkzQ5BW11cetCWusV2Dku1btPTA5Fhs+dvPDlL3m496a3Bq/A/fRDj5JLDiiPibvpM01lEBxFKYooWGQ75HVuhnAt57vabD45gDpIE7N23+So4+9bsG/nT/ZlgoaS01uLTdlnf6tjNgP0/UBkonmedC62iVvCu7itfHZMTY2rSeww7KBMI3s7Gz+cyx9IbI3shbDpdJGHpM8Qe+1oFi31Z+DylWQA5SkpHlLMUP+zjMKLF+1hXGNUeJuyadIFrxzbS3vTV2yRPa6ol8q+bX7YLy0xNLSE8aMm54LKgXfRKLc3G8d3I33oEfyk5hygY8iEX728r2TsARslYxOF3sZqJvY8lx4GBEDiXxX2GJvGCPy/Uby786uWnZlFFkDERk3nawE0W68zY0GElbutq6HMSk6v49J7em9Rg/QLptjoa0uF2A9Cy+BAJcnfauIawOG3UPXZ8kD60PTbu8tqtwtXO5lzTSIOr1lt3+6R8GmCc2hz2YXELKvdnZWYCXAjnNuC4eESlp7zxmzhpOVkb2Jy1v6rGKpcxVMggLQbOjOGWPLg9q4+OZQBw5bhMGmVGQhSBuxzEb/wBRy9XV8=
      on:
        tags: true

    - provider: releases # upload tarball and zip with source code
      skip_cleanup: true
      overwrite: true
      file:
        - $TRAVIS_BUILD_DIR/segyio-$VERSION.tar.gz
        - $TRAVIS_BUILD_DIR/segyio-$VERSION.zip
      api_key:
        secure: VdV/5kCCwUFwgU7wvKRrOy4u9nnvLsM3RoW1G2z8w8e838fcTeXLU3Zu8rLzLpcaXJKX07WNQmG85PZrgRjB9mzZAbXnPJeMk5MT3YVWaiyF6zNxK+mQQOvTCJ8P25nm5Iq1PLtIW/wM1RqNLgT8t3AsLiIva+6JK+2wGA2ilOl2YVgJqEiZV1f9DJutPewDf8pqYrnrHktMmkio/uubc12MLFOrNeQxK/EJahw7x56q8EcxrJXHnv6T2zEvUdcEYfRvIrT62jiVqiJP9wmUVdq2x8/RlgRzcCpGhy2o17iMUIH228so2hbu5/NcvtAh/LUDeqlhQ1YLRp1vO6H8Uh9B6aJgBNPwYmrKBHQQD27l5vt74DNJuqsXTZtrQlzUiiptKTV7mjFckF7mG04d1J/0GcVcxjpRZa3rp85KymQKWTsuWJYrCWSeVh+SMwUAbMZ3/vhEKPtrf4rwI+4INTitLuBNfcyH0W+W/rWLBMYoojRW0NJjc+4HJGpkMPbFkDjpde31ZqgI/Cec0GPpqbtsb3DkK/f4mLrR+F59b3+Lj0Cjyh9lM2fVXTrPYt13kdwbtBnNy6x2kdTkEBCk9m+eTFAfJGal+3SwgLeiGQdkjdZ7vSLwwdRf7Qvz5WjxKQ+feFWm+qi0GurWOEaZrubB82CGukxOXKzrvAGN3Eo=
      on:
        tags: true
        condition: $TRAVIS_OS_NAME == linux && $MB_PYTHON_VERSION == 3.6
